import fs from 'fs'
import { fullMatrix, PAINT } from './state-matrix.mjs'
import { pretty } from './resolve-tokens.mjs'

const REF = process.env.REF
const page = process.argv[2]
const specs = JSON.parse(fs.readFileSync(process.argv[3], 'utf8'))
let html = fs.readFileSync(`${REF}/${page}`, 'utf8')

const MARK = 'GENERATED:matrix-css'
const STYLE = `
/* ${MARK} — regenerated by scripts/inject-matrix.mjs, do not hand-edit */
.mx { margin-top: var(--space-4); border-top: 1px dashed var(--color-border-default); padding-top: var(--space-4); }
.mx > h3 { font-size: var(--text-11); text-transform: uppercase; letter-spacing: 0.06em; color: var(--color-ink-tertiary); margin: 0 0 var(--space-3); }
.mxwrap { overflow-x: auto; }
.mxtbl { border-collapse: collapse; }
.mxtbl th { font-size: var(--text-11); text-transform: uppercase; letter-spacing: 0.04em; color: var(--color-ink-tertiary); font-weight: var(--weight-semibold); text-align: left; padding: 0 14px 6px 0; }
.mxtbl td { padding: 9px 14px 9px 0; border-top: 1px solid var(--color-border-subtle); vertical-align: top; }
.mxtbl td.rowh { font-family: var(--font-mono); font-size: var(--text-11); color: var(--color-primary-default); white-space: nowrap; padding-top: 15px; padding-right: var(--space-4); }
.mxcell .chip { display: inline-flex; align-items: center; justify-content: center; gap: var(--space-2); white-space: nowrap; border-style: solid; }
.mxcell .chip svg { width: max(.85em, 11px); height: max(.85em, 11px); fill: currentColor; flex: 0 0 auto; }
.mxcell .chip .slot { display: inline-flex; align-items: center; gap: 4px; padding-left: 6px; margin-left: 2px; border-left: 1px solid currentColor; opacity: .55; }
.mxvals { margin-top: 6px; font-family: var(--font-mono); font-size: 10px; line-height: 1.55; color: var(--color-ink-tertiary); }
.mxvals b { color: var(--color-ink-secondary); font-weight: var(--weight-medium); }
.mxsame { font-size: var(--text-11); color: var(--color-ink-tertiary); font-style: italic; margin-top: 4px; }
`
// Replace, never skip. A presence check here meant every later run silently kept the
// first run's CSS, so edits to the rules above never reached the page and the icons
// rendered at zero size.
const block = new RegExp(`\\n?/\\* ${MARK}[\\s\\S]*?/\\* END ${MARK} \\*/`, 'g')
html = html.replace(block, '')
html = html.replace('</style>', `${STYLE}/* END ${MARK} */\n</style>`)

const PLUS =
  '<svg viewBox="0 0 448 512"><path d="M256 80c0-17.7-14.3-32-32-32s-32 14.3-32 32l0 144L48 224c-17.7 0-32 14.3-32 32s14.3 32 32 32l144 0 0 144c0 17.7 14.3 32 32 32s32-14.3 32-32l0-144 144 0c17.7 0 32-14.3 32-32s-14.3-32-32-32l-144 0 0-144z"/></svg>'
const PEN =
  '<svg viewBox="0 0 512 512"><path d="M410.3 231l11.3-11.3-33.9-33.9-62.1-62.1L301.5 89.8l-11.3 11.3-22.6 22.6L58.6 332.6c-10.4 10.4-18 23.3-22.2 37.4L1 488.5c-2.5 8.4-.2 17.5 6.1 23.7s15.3 8.5 23.7 6.1l118.5-35.4c14.1-4.2 27-11.8 37.4-22.2L414.4 253.7 410.3 231z"/></svg>'
const TRASH =
  '<svg viewBox="0 0 448 512"><path d="M135.2 17.7L128 32 32 32C14.3 32 0 46.3 0 64S14.3 96 32 96l384 0c17.7 0 32-14.3 32-32s-14.3-32-32-32l-96 0-7.2-14.3C307.4 6.8 296.3 0 284.2 0L163.8 0c-12.1 0-23.2 6.8-28.6 17.7zM416 128L32 128 53.2 467c1.6 25.3 22.6 45 47.9 45l245.8 0c25.3 0 46.3-19.7 47.9-45L416 128z"/></svg>'
const DOT = '<span style="width:12px;height:12px;border-radius:999px;background:#aa1055;flex:0 0 auto"></span>'

let done = 0
for (const [heading, spec] of Object.entries(specs)) {
  const rows = fullMatrix(spec)
  const states = spec.states

  let t = '      <div class="mxwrap"><table class="mxtbl"><thead><tr><th></th>'
  for (const s of states) t += `<th>${s ?? 'default'}</th>`
  t += '</tr></thead><tbody>\n'

  for (const row of rows) {
    const wantsIcon = spec.glyph === 'always' || row.combo.some(c => c.prop === 'icon' && c.value === true)
    const wantsLead = row.combo.some(c => c.prop === 'leading' && c.value === true)
    const wantsActions = row.combo.some(c => c.prop === 'actions' && c.value === true)
    t += `        <tr><td class="rowh">${row.label}</td>`
    for (const cell of row.cells) {
      const v = cell.values
      const px = k => (v[k] !== undefined ? pretty(v[k]) : null)
      const style = [
        `background:${px('background') ?? px('background-color') ?? 'transparent'}`,
        `color:${px('color') ?? 'inherit'}`,
        `border-width:1px`,
        `border-color:${px('border-color') ?? 'transparent'}`,
        `border-radius:${px('border-radius') ?? '9999px'}`,
        `height:${px('height') ?? '40px'}`,
        `padding:${px('padding') ?? '0 20px'}`,
        `font-size:${px('font-size') ?? '14px'}`,
        `font-weight:${px('font-weight') ?? '600'}`,
        `font-family:var(--font-sans)`,
        v.opacity ? `opacity:${pretty(v.opacity)}` : '',
        v['box-shadow'] ? `box-shadow:${pretty(v['box-shadow'])}` : '',
      ]
        .filter(Boolean)
        .join(';')
      const vals = PAINT.filter(k => v[k] !== undefined && k !== 'border')
        .map(k => `<b>${k}</b> ${pretty(v[k])}`)
        .join('<br>')
      const same = !cell.differs ? '<div class="mxsame">same as default — no frame needed</div>' : ''
      const lead = wantsLead ? DOT : ''
      const actions = wantsActions ? `<span class="slot">${PEN}${TRASH}</span>` : ''
      t += `<td class="mxcell"><span class="chip" style="${style}">${wantsIcon ? PLUS : ''}${lead}${spec.label ?? 'Label'}${actions}</span>${same}<div class="mxvals">${vals}</div></td>`
    }
    t += '</tr>\n'
  }
  t += '      </tbody></table></div>\n'

  const cells = rows.flatMap(r => r.cells)
  const distinct = cells.filter(c => c.differs).length
  const note = `      <p class="frames">${rows.length} combinations × ${states.length} state${states.length === 1 ? '' : 's'} = ${cells.length} cells; <b>${distinct} need a frame</b> — the rest repeat the default.</p>\n`
  const block = `    <div class="mx">\n      <h3>Every variant × state, rendered</h3>\n${t}${note}    </div>\n  `

  const i = html.indexOf(`<h2>${heading}`)
  if (i === -1) {
    console.log('  no heading:', heading)
    continue
  }
  const secEnd = html.indexOf('</section>', i)
  if (html.slice(i, secEnd).includes('class="mx"')) {
    console.log('  already:', heading)
    continue
  }
  html = html.slice(0, secEnd) + block + html.slice(secEnd)
  done++
}
fs.writeFileSync(`${REF}/${page}`, html)
console.log(`${done} sections given a rendered matrix`)
